
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: foo-default
spec:
  hosts:
  - bar.foo.com
  gateways:
  - foo-com-gateway
  http:
  - match:
    - uri:
        prefix: /whiz
    route:
    - destination:
        host: whiz.foo.svc.cluster.local
  - route:
    - destination:
        host: bar.foo.svc.cluster.local